name: audio_recorder_example
description: Demonstrates how to use the audio_recorder plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  file: ^6.1.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.8
  audio_recorder_nullsafety:
    path: ../

dev_dependencies:
  
  flutter_test:
    sdk: flutter
  lint: ^1.8.1

flutter:
  uses-material-design: true
