name: audio_recorder_example
description: Demonstrates how to use the audio_recorder plugin.

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  file: ^6.1.0
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

dev_dependencies:
  audio_recorder:
    path: ../
  flutter_test:
    sdk: flutter
  lint: ^1.5.2

flutter:
  uses-material-design: true
