name: audio_recorder
description: A Flutter plugin to record audio.
version: 1.0.2
homepage: https://github.com/ZaraclaJ/audio_recorder

dependencies:
  file: ^6.0.0
  flutter:
    sdk: flutter
  path: ^1.8.0

environment:
  sdk: '>=2.12.0 <3.0.0'

flutter:
  plugin:
    androidPackage: com.jordanalcaraz.audiorecorder.audiorecorder
    pluginClass: AudioRecorderPlugin

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.2
  path_provider: ^2.0.1
  test: ^1.16.5
